[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "recover"
path = "src/recover.rs"

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
hex = "0.4.3"
protocol = { path = "../protocol" }
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
